# Generated by Django 3.0.7 on 2020-06-12 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_posts',
            new_name='Posts',
        ),
    ]
