# Generated by Django 3.0.7 on 2020-06-12 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200613_0032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Blog',
        ),
    ]
